import type { CaptionStyle, Template } from '../types'

/** Sensible default style used as the base for every template. */
export const DEFAULT_STYLE: CaptionStyle = {
  fontFamily: 'Montserrat',
  fontWeight: 900,
  fontSize: 7,
  uppercase: true,
  letterSpacing: 0,
  lineHeight: 1.1,

  color: '#ffffff',
  highlightColor: '#ffe14d',
  highlightMode: 'color',
  highlightBg: '#7c5cff',

  outlineWidth: 6,
  outlineColor: '#000000',
  shadow: true,
  shadowColor: '#000000',

  bgEnabled: false,
  bgColor: '#000000',
  bgOpacity: 0.55,
  bgPaddingX: 0.6,
  bgPaddingY: 0.3,
  bgRadius: 0.4,

  positionY: 78,
  maxWords: 4,

  entrance: 'pop',
  wordReveal: 'word',
}

function make(base: Partial<CaptionStyle>): CaptionStyle {
  return { ...DEFAULT_STYLE, ...base }
}

export const TEMPLATES: Template[] = [
  {
    id: 'ugc-pop',
    name: 'UGC Bold Pop',
    tag: 'UGC',
    description: 'Heavy Montserrat, yellow active word, pop-in. The viral classic.',
    style: make({
      fontFamily: 'Montserrat',
      fontWeight: 900,
      uppercase: true,
      color: '#ffffff',
      highlightMode: 'color',
      highlightColor: '#ffe14d',
      outlineWidth: 7,
      entrance: 'pop',
      wordReveal: 'word',
      maxWords: 4,
      fontSize: 7.5,
    }),
  },
  {
    id: 'ugc-boxed',
    name: 'Green Box Karaoke',
    tag: 'UGC',
    description: 'Active word gets a rounded highlight box. High retention.',
    style: make({
      fontFamily: 'Montserrat',
      fontWeight: 900,
      uppercase: true,
      color: '#ffffff',
      highlightMode: 'box',
      highlightBg: '#22c55e',
      highlightColor: '#0a0a0f',
      outlineWidth: 5,
      entrance: 'none',
      wordReveal: 'chunk',
      maxWords: 3,
      fontSize: 7,
    }),
  },
  {
    id: 'ugc-anton',
    name: 'Impact Anton',
    tag: 'UGC',
    description: 'Tall condensed Anton with a scale punch on each word.',
    style: make({
      fontFamily: 'Anton',
      fontWeight: 400,
      uppercase: true,
      color: '#ffffff',
      highlightMode: 'scale',
      highlightColor: '#ff4d4d',
      outlineWidth: 6,
      entrance: 'bounce',
      wordReveal: 'word',
      maxWords: 3,
      fontSize: 9,
      letterSpacing: 0.5,
    }),
  },
  {
    id: 'vsl-clean',
    name: 'Clean VSL',
    tag: 'VSL',
    description: 'Legible Inter, subtle fade, one line at a time. Trustworthy.',
    style: make({
      fontFamily: 'Inter',
      fontWeight: 800,
      uppercase: false,
      color: '#ffffff',
      highlightMode: 'color',
      highlightColor: '#5ac8fa',
      outlineWidth: 0,
      shadow: true,
      bgEnabled: true,
      bgColor: '#000000',
      bgOpacity: 0.5,
      entrance: 'fade',
      wordReveal: 'chunk',
      maxWords: 6,
      fontSize: 5,
      positionY: 82,
    }),
  },
  {
    id: 'vsl-lower',
    name: 'VSL Lower Third',
    tag: 'VSL',
    description: 'Oswald in a solid bar near the bottom. Documentary feel.',
    style: make({
      fontFamily: 'Oswald',
      fontWeight: 700,
      uppercase: true,
      color: '#ffffff',
      highlightMode: 'none',
      outlineWidth: 0,
      shadow: false,
      bgEnabled: true,
      bgColor: '#0a0a0f',
      bgOpacity: 0.8,
      bgPaddingX: 0.9,
      bgPaddingY: 0.35,
      bgRadius: 0.2,
      entrance: 'slide-up',
      wordReveal: 'chunk',
      maxWords: 7,
      fontSize: 4.5,
      positionY: 85,
      letterSpacing: 0.5,
    }),
  },
  {
    id: 'ads-friendly',
    name: 'Friendly Ad',
    tag: 'Ads',
    description: 'Rounded Fredoka with a purple pill highlight. Playful & modern.',
    style: make({
      fontFamily: 'Fredoka',
      fontWeight: 700,
      uppercase: false,
      color: '#ffffff',
      highlightMode: 'box',
      highlightBg: '#7c5cff',
      highlightColor: '#ffffff',
      outlineWidth: 4,
      entrance: 'bounce',
      wordReveal: 'word',
      maxWords: 4,
      fontSize: 6.5,
    }),
  },
  {
    id: 'ads-rubik',
    name: 'Bold Ad',
    tag: 'Ads',
    description: 'Punchy Rubik, white text, cyan pop word. Great for CTAs.',
    style: make({
      fontFamily: 'Rubik',
      fontWeight: 800,
      uppercase: true,
      color: '#ffffff',
      highlightMode: 'color',
      highlightColor: '#00e0d5',
      outlineWidth: 6,
      entrance: 'pop',
      wordReveal: 'word',
      maxWords: 4,
      fontSize: 6.5,
    }),
  },
  {
    id: 'minimal',
    name: 'Minimal Mono',
    tag: 'Ads',
    description: 'Simple white words, no outline, gentle fade. Understated.',
    style: make({
      fontFamily: 'Poppins',
      fontWeight: 700,
      uppercase: false,
      color: '#ffffff',
      highlightMode: 'none',
      outlineWidth: 0,
      shadow: true,
      entrance: 'fade',
      wordReveal: 'chunk',
      maxWords: 6,
      fontSize: 4.5,
      positionY: 80,
    }),
  },
]
